### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by deadsoul44** [MaikuB/supnews#5]
There is no tutorial about how to test rest api calls with mobx on web. Could you please add tests?

**Comment by MaikuB** [comment]
Not something I'm going to get around to doing. From what you said, sounds like part of the problem here is you're trying to do a search for something that is MobX-specific. You should be looking into the fundamentals of unit testing that involve abstractions, creating fakes etc. 
If you haven't already, then you should read  https://flutter.dev/docs/cookbook/testing/unit/mocking. I also recommend reading the Art of Unit Testing book by Roy Osherove. These will teach you universal concepts that you should be looking to apply
